### PR TITLE
fix: npm audit fix --force (CUR-69)

### PR DESCRIPTION
**Pull request by mgabeler-lee-6rs**

### CODE REVIEW

**Comment by asdo6rs** [comment]
Should we update @types/mocha while we're at it?

**Comment by tonygaetani** [comment]
Or maybe mocha is written in typescript now so we don't need @types/mocha - if so then we should remove @types/mocha

So yeah, I think either updating or removing @types/mocha would make sense. Thoughts @mgabeler-lee-6rs ?

**Comment by mgabeler-lee-6rs** [comment]
Well, that end up being a baby yak shave ... ended up updating eslint, typescript, and node too...

**Comment by mgabeler-lee-6rs** [comment]
I didn't update some things "all the way", e.g. I stopped `typescript` at the version the WFM uses right now because Paranoid

**Comment by asdo6rs** [comment]
That looks good.  Did you run something to reorganize the imports?  I thought we'd get that when we updated to prettier, but I didn't see that in the changes.

**Comment by mgabeler-lee-6rs** [comment]
import order comes from our new eslint config, which I did update

**Comment by tonygaetani** [comment]
LGTM

**Pull request merged**
